#! /bin/bash
#
#$Author: ee364a07 $
#$Date: 2016-08-23 10:35:18 -0400 (Tue, 23 Aug 2016) $
#$Revision: 91031 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F16/students/ee364a07/Lab00/Script1 $
#$Id: Script1 91031 2016-08-23 14:35:18Z ee364a07 $

Num_Of_Param=$#
Param_Values=$@
echo "The program received $Num_Of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
