#! /bin/bash
#
#$Author: ee364a07 $
#$Date: 2016-08-23 10:47:37 -0400 (Tue, 23 Aug 2016) $
#$Revision: 91052 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F16/students/ee364a07/Lab00/Script3 $
#$Id: Script3 91052 2016-08-23 14:47:37Z ee364a07 $

Value=$1
Count=$Value
while (($Count >= 0))
do
    if (($Count % 3 == 0))
    then
        echo "$Count"
    fi
    ((Count=$Count - 1))
done
